# Site settings
title: ManhNT's blog | On software 'n programming
description: "Description place holder"
url: "http://manhnt.github.io/"
author:
  name: "ManhNT"
  email: "manhnt1991@gmail.com"
  url: "http://manhnt.github.io/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Plugins
gems: [jekyll-paginate]

# Options
custom_header: false
custom_nav_footer: true
reverse: false

