title: Manh Nguyen
description: Blog on Software Development
author: Manh Nguyen
github: https://github.com/manhnt
about: Software Engineer
disqus_shortname: http-manhnt-github-io
google_analytics: UA-80611911-1

urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-stack-exchange
      link: 'https://stackoverflow.com/users/1275831/theman?tab=profile'
    - icon: fa-github
      link: 'https://github.com/manhnt'

enableTags: true
tagarray: []

url: "https://manhnt.github.io"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

